### ISSUE TITLE
Make error messages better

### ISSUE THREAD

**Issue by MatrixTunnel** [Minehut/MinehutBOTOld#9]
Looks like trash right now :P
![image](https://user-images.githubusercontent.com/13736303/28595966-2d169c02-714b-11e7-9b34-281e0a153db4.png)

**Comment by Bryan3838** [comment]
hi
~ mr.wail

**Comment by Sniped** [comment]
> Amount of people boosting the server and how many people stop/start boosting the server.

Discord JS hasn't added anything for boosting, we can however track the role adding of "Nitro Booster", there's an event for that and represents when someone boosts and unboosts.

**Comment by BennyDoesStuff** [comment]
Yeah, that definitely could work out.
